[BACKEND] bump to most recent working LLVM commit 2fe947b477 (#5591)
I have "bisected" the current CUDA regression (mentioned
[here](https://github.com/triton-lang/triton/pull/5341)) on A100:

```
git bisect start
# bad: [f5a35a31bfe6cbc16bec0c130f2bb3632dbf1fbf] [LV] Add test cases with incorrect IV live-outs.
git bisect bad f5a35a31bfe6cbc16bec0c130f2bb3632dbf1fbf
# good: [86b69c31642e98f8357df62c09d118ad1da4e16a] [SPIR-V] Fix SPIR-V extension SPV_INTEL_function_pointers: 
...
# first bad commit: [b8703369daf777706196ff914c0376c27adde3cf] [SLP] Match poison as instruction with the same opcode
```

The failure presents as :

```
Traceback (most recent call last):
  File "/home/mleventa/dev_projects/repro/repro.py", line 135, in <module>
    torch.cuda.synchronize()
  File "/home/mleventa/dev_projects/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 987, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
```

The failing commit is
[`b870336`](https://github.com/llvm/llvm-project/pull/115946) and the
last working commit is `2fe947b4`. It's not clear to me the relationship
but will investigate.

This PR to `llvm-head` is to verify that my repro on A100 matches the
internal regression/fail.