[FRONTEND] add architecture to hash to avoid invalid image on cubin load (#1593)
Closes https://github.com/openai/triton/issues/1556
https://github.com/openai/triton/issues/1512

The current hash used for caching the cubin does not include the
architecture. This leads to the following error when compiling against
one arch and running against another (with no code changes to trigger a
recompilation).
```
RuntimeError: Triton Error [CUDA]: device kernel image is invalid
```
Was not sure what unit tests would be appropriate here (if any)

Co-authored-by: davidma <davidma@speechmatics.com>