Change to torch.testing.assert_close()
I fill alto=1e-5, which is the default value of float32, or an error is
raised.

ValueError: Both 'rtol' and 'atol' must be either specified or omitted, but got no atol.