[CI] Fix `du` failling if cache restore fails
It's currently failing with the error
```
du: /Users/runner/.triton/**: No such file or directory
Error: Process completed with exit code 1.
```
which happens because even though the `.triton` directory exists,
it is empty. This instead uses du on `.triton` with a depth of 1.