[DOC] Update the testing instructions.
This commit updates the testing instructions in the readme file. The two
missing packages are used by triton in "triton/testing.py". Without
these dependencies users get the following error:

Traceback (most recent call last):
  File "/home/..../test/test.py", line 133, in <module>
    benchmark.run(print_data=True, show_plots=True)
  File "/home/..../triton/python/triton/testing.py", line 346, in run
    result_dfs.append(self._run(bench, save_path, show_plots, print_data, **kwargs))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/..../triton/python/triton/testing.py", line 272, in _run
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'