[CUDA][rel/3.7] Cherrypick two commits that are necessary for PyTorch CUDA Binaries especially for GB300/Spark/THOR (#9621)
Context: https://github.com/pytorch/pytorch/issues/173702 

<!---
The core Triton is a small number of people, and we receive many PRs
(thank
you!).  To help us review your code more quickly, **if you are a new
contributor (less than 3 PRs merged) we ask that you complete the
following
tasks and include the filled-out checklist in your PR description.**

Complete the following tasks before sending your PR, and replace `[ ]`
with
`[x]` to indicate you have done them.
-->

# New contributor declaration
- [X] I am not making a trivial change, such as fixing a typo in a
comment.

- [X] I have written a PR description following these
  [rules](https://cbea.ms/git-commit/#why-not-how).

- [ ] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.

- Select one of the following.
  - [ ] I have added tests.
    - `/test` for `lit` tests
    - `/unittest` for C++ tests
    - `/python/test` for end-to-end tests
  - [ ] This PR does not need a test because `FILL THIS IN`.
Existing tests plus additional nvidia tests (due to runner not available
in public) should cover the tests aspects.

- Select one of the following.
  - [X ] I have not added any `lit` tests.
- [ ] The `lit` tests I have added follow these [best
practices](https://mlir.llvm.org/getting_started/TestingGuide/#filecheck-best-practices),
including the "tests should be minimal" section. (Usually running Python
code
    and using the instructions it generates is not minimal.)

======
** Why do we need the 80d7aff4902dbd92e75bb32fb8934ae874b59d67 commit?
**
There has been LLVM change
https://github.com/llvm/llvm-project/pull/180116 that has been picked up
by existing rel/3.7 by
https://github.com/triton-lang/triton/commit/731540ba90107cb8807ce0aa21073b9464ee6d3b
Due to this update, if we don't include such commits, we would encounter
(depends on different platforms) the following errors

LLVM ERROR: PTX version 8.6 does not support target 'sm_110a'. Minimum
required PTX version is 9.0. Either remove the PTX version to use the
default, or increase it to at least 9.0.
LLVM ERROR: PTX version 8.6 does not support target 'sm_121a'. Minimum
required PTX version is 9.0. Either remove the PTX version to use the
default, or increase it to at least 8.8.
LLVM ERROR: PTX version 8.6 does not support target 'sm_103a'. Minimum
required PTX version is 9.0. Either remove the PTX version to use the
default, or increase it to at least 8.8.

In particular, see the changes in
llvm/lib/Target/NVPTX/NVPTXSubtarget.cpp

 case SMF(100):
  case SMF(101):
  case SM(103):
  case SMF(103):
  case SMA(103):
  case SMF(120):
  case SM(121):
  case SMF(121):
  case SMA(121):
    return 88;
  case SM(88):
  case SM(110):
  case SMF(110):
  case SMA(110):
    return 90;

** Why do we need the 80d7aff4902dbd92e75bb32fb8934ae874b59d67 commit?
**
The PR description of https://github.com/triton-lang/triton/pull/9499
already mentioned the reason. If we don't cherrypick this change, we
likely will get (unless CUDA has updates on this) the following error

ValueError: CUtensorMap must be aligned to 128B, but got (&map) mod 128
= 64


cc @atalman @malfet @ptrblck @tinglvv @eqy

---------

Co-authored-by: Thomas Raoux <thomas.raoux@openai.com>
Co-authored-by: Tori Baker <vwbaker@google.com>