[DOC][easy] Fix outdated triton.Config argument doc and example (#3671)
### Why?

The example code in
[autotune](https://triton-lang.org/main/python-api/generated/triton.autotune.html#triton.autotune)
fails because of incorrect argument name.

The issue can be easily reproduced by

```python
>>> import triton
>>> triton.Config(meta={'BLOCK_SIZE': 128}, num_warps=4),
TypeError: Config.__init__() got an unexpected keyword argument 'meta'
```

### What?

1. Fix the inline documentation of argument name
2. Fix example code

Co-authored-by: Pin-Lun Hsu <byhsu@linkedin.com>