make directory if needed for saving benchmark results, instead of erring out after benchmark has completed and losing results. (#2796)
quality of life improvement - if user passes in 'save_path' for saving
results of benchmarking,
```
benchmark.run(show_plots=True, print_data=True, save_path='./results')
```

create the directory for them instead of erring out after the run b/c
they didn't make the dir beforehand.

This avoids what I just hit:

```
 html = open(os.path.join(save_path, "results.html"), "w")
FileNotFoundError: [Errno 2] No such file or directory: './results/results.html'
```