[BACKEND] Ignore bad bytes in ldconfig -p (#7566)
`ldconfig -p` can cause failures on EKS / Ubuntu where ldconfig on
/bin/sh is not guaranteed to produce valid utf-8. Just ignore the bad
bytes and parsing is still ok.

This was the error:

```
  libs = subprocess.check_output(["/sbin/ldconfig", "-p"]).decode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 60334: invalid continuation byte
```

# New contributor declaration
Slightly trivial but causing major failures forcing us to parse ldconfig
elsewhere with a parser that can handle bad utf-8?
- [x] I am not making a trivial change, such as fixing a typo in a
comment.

- [x] I have written a PR description following these
  [rules](https://cbea.ms/git-commit/#why-not-how).

- [x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.

- Select one of the following.
  - [ ] I have added tests.
    - `/test` for `lit` tests
    - `/unittest` for C++ tests
    - `/python/test` for end-to-end tests
- [x] This PR does not need a test because `simple parameter addition
which just ignores bad chars in python stdlib`

- Select one of the following.
  - [X] I have not added any `lit` tests.
- [ ] The `lit` tests I have added follow these [best
practices](https://mlir.llvm.org/getting_started/TestingGuide/#filecheck-best-practices),
including the "tests should be minimal" section. (Usually running Python
code
    and using the instructions it generates is not minimal.)