[AMD] Fix multiple driver.py compiler warnings/errors (#7838)
The refactor to driver.py seemed to create multiple conventions that
violate our default compiler warning. Here is a description:

```
__triton_launcher.c:170:5: error: no matching function for call to 'PyFloat_Pack2'
  170 |     PyFloat_Pack2(f, (unsigned char*)&result, 1);
  ```

See this definition: https://docs.python.org/3/c-api/float.html. Should be just char*

```
__triton_launcher.c:141:5: error: cannot jump from this goto statement
to its label
  141 |     goto cleanup;
      |     ^
__triton_launcher.c:152:14: note: jump bypasses variable initialization
152 | hipError_t status =
hipSymbolTable.hipPointerGetAttribute(&dev_ptr,
HIP_POINTER_ATTRIBUTE_DEVICE_POINTER, ptr_info.dev_ptr);
  ```
  
  Fixed by declaring status at the top of the function.