Fix gluon attention example for fp8 (#10399)
Currently, running `python
python/examples/gluon/01-attention-forward.py` fails with

```
python/examples/gluon/01-attention-forward.py:386:14: error: source and result must have the same logical storage size (4096 vs 2048)
    p_tmem = s_tmem._reinterpret(config.dtype, [config.SPLIT_M, 2 * config.BLOCK_N], config.p_tmem_layout)
```

This happens when the benchmark is run with fp8. `pytest
python/examples/gluon/01-attention-forward.py` doesn't fail simply
because it doesn't test on fp8.

The regression is from https://github.com/triton-lang/triton/pull/10243
but the problematic code hardcoding a fixed column count like
`config.BLOCK_N // 2` has been there for a long time. Previously it only
worked due to the loose convention on reinterpret.