[Gluon] Fix auto_encoding for ops which may infer multiple layouts (#7718)
In the failing example we have:
```mlir
    %0 = tt.make_range {end = 8192 : i32, start = 0 : i32} : tensor<8192xi32, #gluon.auto_encoding>
    %1 = tt.reshape %0 : tensor<8192xi32, #gluon.auto_encoding> -> tensor<64x128xi32, #gluon.auto_encoding>
    %2 = gluon.set_auto_layout %1 : tensor<64x128xi32, #gluon.auto_encoding> -> tensor<64x128xi32, #blocked>
```
which currently fails with the error:
```python
/root/code/triton/test.py:43:52: error: 'tt.reshape' op Found conflicting encodings for value
            gl.arange(0, BLOCK_M * BLOCK_N).reshape((BLOCK_M, BLOCK_N)),
```

The issue is that we propagate the blocked layout backwards to get a
linear layout for the `make_range` result, then the algorithm propagates
that layout forward to the `reshape` result. However, it infers a linear
layout and errors because it conflicts with the original blocked layout.

I fix this by setting a `mayVary` flag when an encoding comes from an
inference result that isn't the only possibility. I then have special
rules that resolve conflicts where one or more of the encodings is
allowed to vary.