[Bug fix] tl.dot(a, b, None) (#7130)
If user passes None explicitly to `acc` in tl.dot, it will fail when
accessing acc.handle from a constexpr[None].

```
        if acc is None:
            acc_handle = builder.create_splat(ret_ty.to_ir(builder), _0)
        else:
>           acc_handle = acc.handle
E           AttributeError: 'constexpr' object has no attribute 'handle'
```

Test plan:
1. randomly pick a unit test `pytest
python/test/unit/language/test_core.py::test_dot[1-32-32-32-4-False-False-add-cols-ieee-float16-float16-1-None]`
2. add None to tl.dot