[AMD] Fix tt.fp_to_fp bf16 to fp32 conversion (#4238)
Added missing handling of tt.fp_to_fp in
FpToFpOpConversion::createDestOps when type of src operand is bf16 and
type of dst operand is fp32.

When having tt.fp_to_fp with src type bf16 and dst operand of type fp32,
there were following error message:
error: failed to legalize operation 'tt.fp_to_fp' that was explicitly
marked illegal

BF16 to FP16 (FP32) was not handled neither in 
FpToFpOpConversion::createDestOps nor in getConversionFunc,
thus conversion is added directly in FpToFpOpConversion::createDestOps, 
similarly, as for the case when source and destination operands are of
the same type.