[INTERPRETER] Validate TensorHandle np/tl dtypes size (#8594)
Continuation of https://github.com/triton-lang/triton/pull/8550

Converting `np.dtype` to `tl.dtype` in automatic way seems too intrusive
due to `pointer_type` and fp8 variants which all are being stored as
`np.uint8`

Easier way achieving the same goal seems to be element's size
validation.

---------------------------------------------------

Looks like there are some other potential data corruptions hidden

Briefly looking they all have the same cause by numpy data promotion
rules.
Example for some binary op like `np.bitwise_and` where inp1 is `int8`
and inp2 is `uint8` result will be promoted to `int16`

```python
import numpy as np
a = np.int8(1)
b = np.uint8(1)
c = np.bitwise_and(a, b)

print(c.dtype) # int16
```

```
FAILED language/test_core.py::test_abs_fp8[in_dtype0] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (16 bits) exceeds dtype primitive_bitwidth (8 bits) for triton type fp8e4b15')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_pos-acquire] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-max_pos-release] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-min_neg-None] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_neg-release] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-max_pos-acq_rel] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-max_pos-relaxed] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_pos-release] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-min_neg-acquire] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_neg-None] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_pos-acq_rel] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_min_max_neg_zero - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_pos-relaxed] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-min_neg-release] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_neg-acq_rel] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_neg-acquire] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-min_neg-acq_rel] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_neg-relaxed] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-all_pos-None] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-min_neg-relaxed] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-max_pos-None] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_atomic_rmw[min-float32-max_pos-acquire] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
FAILED language/test_core.py::test_tensor_atomic_rmw_block[1] - triton.runtime.errors.InterpreterError: ValueError('data itemsize (64 bits) exceeds dtype primitive_bitwidth (32 bits) for triton type uint32')
```

cc @Jokeren