Fix default FMA implementation for tensors with integer elements (#7419)
Several examples from our repo:
```bash
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-True-none-tf32-int8-int8-1-None0] - RuntimeError: PassManager::run failed
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-True-none-tf32-int8-int8-1-None1] - RuntimeError: PassManager::run failed
FAILED language/test_core.py::test_dot[1-128-256-32-8-True-False-none-tf32-int8-int8-1-None0] - RuntimeError: PassManager::run failed
```

Most likely you use a different implementation in such cases. I could
add a test for such cases, but need to somehow disable more advanced
implementations (I'm not sure what the good way to do this is).

---------

Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>